baseURL: "https://www.papernote.cn/"
title: Ayala的小站
paginate: 8
theme: PaperMod
languageCode: "zh_CN"
copyright: "© 2017-2023 **[Ayala的小站](https://www.papernote.cn)** | [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) |"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ayala的小站 | 至繁归于简
  description: "Good，欢迎来到Ayala的博客！ 博主00后天蝎座一枚，现处大四，地处美丽的江南水乡，Ayala是我的昵称。 在这里，我会分享我的爱好、我的生活以及一些知识，欢迎大家多多来访并作出评论。 另外，欢迎友链。"
  keywords: [博客, 前端, 手工, 计算机, AyalaKaguya]
  author: AyalaKaguya
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  languageAltTitle: Chinese

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  homeInfoParams:
    Title: "欢迎来到Ayala的博客 \U0001F44B"
    Content: "博主01后天蝎座一枚，现处大四，地处美丽的江南水乡，Ayala是我的昵称。 在这里，我会分享我的爱好、我的生活以及一些知识，欢迎大家多多来访并作出评论。 另外，欢迎友链。"

  socialIcons:
    - name: github
      url: "https://github.com/AyalaKaguya"
    - name: email
      url: "mailto:papermo.io@gmail.com"
    - name: rss
      url: "https://www.papernote.cn/index.xml"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai

menu:
  main:
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 10
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 30
    - identifier: search
      name: 搜索
      url: /search/
      weight: 40
    # - identifier: donate
    #   name: 赞助
    #   url: /donate/
    #   weight: 50
    - identifier: links
      name: 友链
      url: /friends/
      weight: 60

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
